# SPDX-FileCopyrightText: Copyright (c) 2020-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.23.1
install: |-
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
merge:
  script: |-
    bundle update
    bundle exec jekyll build
